### ISSUE TITLE
compass-import-once breaks sass-globbing

### ISSUE THREAD

**Issue by lolmaus** [Compass/compass#1529]
[sass-globbing](https://github.com/chriseppstein/sass-globbing)'s `@import subdir/*.*` doesn't import anything when [compass-import-once](https://github.com/chriseppstein/compass/tree/master/import-once) is activated.

Not sure which issue queue this ticket should belong to.

**Comment by chriseppstein** [comment]
Sigh. Thanks for the report, will investigate.

**Comment by aaronjensen** [comment]
just ran into this one as well. I looked into it briefly but no luck.

**Comment by aaronjensen** [comment]
ok, so I don't know what the fix is, but the problem appears to be that sass-rails sets the `filename` in the `options` of the `Sass::Engine` to be `base_pathname.to_s` for the glob statement. Because that's the file that is being processed, import-once thinks it was already imported. 

I don't know if there would be a way for import-once to tell that the engine it is getting back is a glob expansion and it should therefore ignore the tracker... sass-rails could set a flag that import-once would look for, but I'm not sure that much coupling is the right approach.

**Comment by aaronjensen** [comment]
Here's monkey patch/hack workaround. Throw this in an initializer:

```
      Sprockets::SassImporter.class_eval do
        protected
        def glob_imports_with_tracker_invalidation(glob, base_pathname, options)
          engine = glob_imports_without_tracker_invalidation(glob, base_pathname, options)
          if engine
            tracker(options).delete import_tracker_key(engine, options)
          end
          engine
        end
        alias_method_chain :glob_imports, :tracker_invalidation
      end
```

**Comment by pprince** [comment]
I have also now run into this.  I've had no luck thus far in figuring out which one broke what.

**Comment by aaronjensen** [comment]
> I have also now run into this. I've had no luck thus far in figuring out which one broke what.

@pprince can you try my monkey patch and see if that helps you? I don't think the fault is in either gem, it's just an unfortunate combination of the two.

**Comment by pprince** [comment]
@aaronjensen I do not immediately understand "throw this in an initializer".

**Comment by aaronjensen** [comment]
Oh, sorry. There would be some nuances to your particular project, so I can give you general instructions but they may not work for various reasons. I also don't recommend monkey patching like this if you're not very familiar w/ the ramifications. It could cause more trouble than it's worth. If you want to continue, probably the safest thing to do would be to put a file in your `lib` folder called `compass_import_once_monkey_patch.rb` with the contents:

``` ruby
  if defined? Sprockets::SassImporter
      Sprockets::SassImporter.class_eval do
        protected
        def glob_imports_with_tracker_invalidation(glob, base_pathname, options)
          engine = glob_imports_without_tracker_invalidation(glob, base_pathname, options)
          if engine
            tracker(options).delete import_tracker_key(engine, options)
          end
          engine
        end
        alias_method_chain :glob_imports, :tracker_invalidation
      end
  end
```

Then add this to your `config/application.rb`:

``` ruby
require File.expand_path('../../compass_import_once_monkey_patch', __FILE__)
```

**Comment by pprince** [comment]
Ah, I believe you're speaking Rails.  I'm not using rails, just compass
(with django and nodejs, because I am a masochist :)

I'll see if I can give it a shot.

Thanks,
-Paul P.

**Comment by aaronjensen** [comment]
Oh, my mistake... I thought this ticket was about sass-rails, since it is broken as well. The fix for sass-globbing would be different since sprockets isn't in play. Same idea probably applies, every time globbing happens it needs to invalidate the key that represents that file in the tracker.

**Comment by chriseppstein** [comment]
Fixed.

**Comment by pprince** [comment]
I have tried with compass installed from git master branch, and I still have the behavior that, if I require compass-import-once, then globbing @imports become no-ops.

No errors, but the @imports don't produce any output.

It works if I do not require compass-import-once in compass config.

Suggest to re-open.

**Comment by omervk** [comment]
I've tried this with the 1.0.4 release and can confirm what @pprince is seeing.

**Comment by aaronjensen** [comment]
This did not fix it for me either. I'm using globbing from sass-rails.

**Comment by fpellanda** [comment]
We use a workaround at the moment by adding an excalation mark to the improt filename.

```
@import "foo/bar/*!"
```

**Comment by fpellanda** [comment]
Why is this a duplicate of style? We have trouble in compass with the Compass::Import::Importer class which seems not to handle the import correct.

Please reopen Issue!

**Comment by lolmaus** [comment]
It has been reopened a month ago and it is also marked as blocking.

**Comment by fpellanda** [comment]
Ah sorry, my fault. Thanks!

**Comment by chriseppstein** [comment]
Fixed by https://github.com/chriseppstein/sass-globbing/commit/1da5d07baf1cae4059082dc859b2b7499cbb495a and 49fdc97032a4b969c3af08a9c18279ab5060ffed

**Comment by lolmaus** [comment]
Thank you, @chriseppstein.

**Comment by aaronjensen** [comment]
@chriseppstein yet to try this out, but should this fix sass-rails too, or will sass-rails need a similar change?

**Comment by chriseppstein** [comment]
Sass-rails has an independent globbing implementation. Afaict, it should work with import-once.

**Comment by aaronjensen** [comment]
@chriseppstein it did not work previously, and since your only change was to sass-globbing, I'm guessing it still doesn't work now. I'm guessing the issue is with sass-rails, so I should open an issue there after confirming it still doesn't work.

**Comment by omervk** [comment]
Thanks, @chriseppstein, it works wonderfully :)
