### ISSUE TITLE
Compass Compile File Permissions

### ISSUE THREAD

**Issue by quasiobject** [Compass/compass#1623]
I upgraded to 0.12.4 on my laptop last night (OS X 10.9.2). Compass was compiling my CSS just fine, but it was writing the compiled CSS file with 600 permissions. Accordingly, Apache threw a 403 and was unable to load the compiled CSS until I set the permissions to 644. However, each subsequent compile changed the permissions back to 600. Downgrading to 0.12.3 resolved the issue.

I tried the same on my desktop this morning (OS X 10.8.5) and didn't have any issues with 0.12.4. I'm assuming it might be the version of Ruby with Mavericks? I don't do anything special with the Ruby that comes bundled with OS X.

OS X 10.9.2 - Ruby 2.0.0p247 (2013-06-27 revision 41674) 
OS X 10.8.5 - Ruby 1.8.7 (2012-02-08 patchlevel 358)

**Comment by mprins** [comment]
see #1615

**Comment by quasiobject** [comment]
Thanks, I did see that. I'm running Compass 0.12.4 with Sass 3.3.1 on OS X 10.8.5 and don't have those issues on that machine. So, downgrading to Sass 3.2.18 wasn't required for the OS X 10.8.5 machine. 

I believe the OS X 10.9.2 machine was running 3.3.3/4.  I'll try downgrading to Sass 3.2.18 on Mavericks.

**Comment by chriseppstein** [comment]
You can't even run compass 0.12 with Sass 3.3, if you're running compass 0.12, it's activating a Sass 3.2 version installed on your system. If you have Sass 3.2.18 or greater (in the 3.2.x line) installed this issue should be fixed. The only platform that continues to have this issue is windows for other reasons.

**Comment by quasiobject** [comment]
Ah, makes sense. I wasn't aware of that. I do indeed have 3.2.18 installed.

**\* LOCAL GEMS ***
sass (3.3.1, 3.2.18, 3.2.14, 3.2.0, 3.2.0.alpha.8)

Thanks for the explanation.

**Comment by ActionScripted** [comment]
Was having the same problem and fixed it by running `gem clean`...which still didn't resolve things. Compass (0.12.4) and Sass (3.3.4, 3.2.17) still writing things out as 600. 

Will downgrade, thanks everyone.

**Comment by quasiobject** [comment]
@ActionScripted I believe you'll want to install 3.2.18, per Chris' explanation.

gem install sass -v 3.2.18

**Comment by ActionScripted** [comment]
@quasiobject: what I ended up doing was removing sass and compass completely, then reinstalled compass to get the dependencies right. Thanks so much!
