### ISSUE TITLE
Sass compile fails on _font-face.scss mixin when default system encoding is not UTF-8

### ISSUE THREAD

**Issue by dparis** [Compass/compass#196]
Using compass with sass version 3.0.18 (Classy Cassidy) on a system where the default is not UTF-8 (US-ASCII for instance) results in an error:

```
error app/stylesheets/screen.scss (Line 18: Invalid US-ASCII character "\xE2")
```

This is due to the unicode character sequence used in the local font-face path (smiley ☺) hack. The haml library currently attempts to enforce the default encoding when parsing sass files, and throws an exception if it can't perform the encoding conversion. This can be overcome by enforcing a UTF-8 charset in the .scss file by adding a @charset declaration. A patch making this change follows, though this may not be an optimal (or even correct) solution. Any feedback would be appreciated.

```
From 3ef55351f25be9cc54a33a205cbfb24b8f1ee777 Mon Sep 17 00:00:00 2001
From: Dylan Paris <dylan.paris+github@gmail.com>
Date: Tue, 21 Sep 2010 17:02:15 -0700
Subject: [PATCH] Added @charset declaration to force UTF-8 encoding on systems with different default encodings

---
 .../stylesheets/compass/css3/_font-face.scss       |    1 +
 1 files changed, 1 insertions(+), 0 deletions(-)

diff --git a/frameworks/compass/stylesheets/compass/css3/_font-face.scss b/frameworks/compass/stylesheets/compass/css3/_font-face.scss
index 7c9030b..292f889 100644
--- a/frameworks/compass/stylesheets/compass/css3/_font-face.scss
+++ b/frameworks/compass/stylesheets/compass/css3/_font-face.scss
@@ -1,3 +1,4 @@
+@charset "UTF-8";
@import "shared";

 // Cross-browser support for @font-face. Supports IE, Gecko, Webkit, Opera.
-- 
1.7.2.2
```

**Comment by chriseppstein** [comment]
fixed in v0.10.6

**Comment by sullimander** [comment]
This issue is back in 0.11.1.  Looks like the fix got reverted.

**Comment by morgoth** [comment]
I opened new issue for this: https://github.com/chriseppstein/compass/issues/377
