### ISSUE TITLE
Bug with transition mixin + transform as property

### ISSUE THREAD

**Issue by aurelien-baudet** [Compass/compass#289]
Hi!

It's not possible to do this:
@include transition-property(transform)

In order to have:
-webkit-transition-property: -webkit-transform;
-moz-transition-property: -moz-transform
...

Instead it generates:
-webkit-transition-property: transform;
-moz-transition-property: transform;
...

Of course the generated css doesn't work

Thanks

**Comment by chriseppstein** [comment]
hmmm. That's certainly annoying. I'd rather not bake-in a list of what properties are prefixed and what aren't. What if there was a `transition-prefixed-property` mixin?

**Comment by aurelien-baudet** [comment]
Yes you can use a special mixin for that, the important is to have the good result for each browser

**Comment by doctyper** [comment]
I was actually just working on a patch for this when I came across this issue. Patch:
https://github.com/doctyper/compass/commit/50c7c551408f3a3e10daa2ab33d55e4a11c3e8c3

As you can see it takes a lot of customization (unless I'm missing some helper functions?) Unfortunately I did have to "bake-in" prefixed properties in order to get the patch to work.

@chriseppstein Thoughts? Would this be a valid workaround or would your suggestion make more sense?

**Comment by ZeeAgency** [comment]
So... what solution do we have today ?

**Comment by davidcalhoun** [comment]
+1

Hope this is fixed soon.

**Comment by scottdavis** [comment]
ping @paulirish you have any input on the way to best implement this? hate to bother you but you seem to have a greater grasp on vendor prefix's then i do

**Comment by paulirish** [comment]
Looking at the hardcoded list of props that are both 1) animatable/transitionable and 2) prefixed we don't end up with many that people are using, aside from `transform`

`background-size` is unprefixed everywhere except ff3.6, same with `box-shadow`. and `font-size-adjust` is ff only and probably not animatable..

(yup. it's not: http://oli.jp/2010/css-animatable-properties/  )

so tbh I think we should just special case "transform" when used in a transition and apply the prefixes automatically.

**Comment by wagenet** [comment]
@paulirish Sounds good. Would love to see this implemented just for the transform case.

**Comment by paulirish** [comment]
Can someone on this thread take a stab at a pull req for this?

**Comment by chriseppstein** [comment]
Oh look a whole guide for contributing to Compass! http://compass-style.org/help/tutorials/contributing/

**Comment by paulirish** [comment]
Fixed now as #728 was pulled?

`\o/`

**Comment by davatron5000** [comment]
+1 for closing this if it's indeed fixed. Also, #260 doesn't seem crucial to this minor release milestone. Seems like the last hurdle to get animations in Compass. Yay!

**Comment by alkaithil** [comment]
When using `@include single-transition(transform, 1s)` I'm still getting 'transform' without prefixes. Prefixes are included when using the `transition` mixin though.

**Comment by lozandier** [comment]
I can confirm the problem still exists after encountering on SassMeister since it doesn't support Autoprefixer yet (good thing I searched for an existing issue). 

I have a quick SassMeister done that demonstrates this issue (replace `+transition(1s all)` with `+transition(1s transform)` to see rotating animation break): http://sassmeister.com/gist/9700278

Compass version `1.0.0.alpha18` was used on SassMeister and offline to reproduce the issue.

**Comment by pr1ntr** [comment]
this still happens for me. 
here is a gist:
http://sassmeister.com/gist/fe5ceb1d1a172abbada1

works fine..
but same code using same versions of sass and compass on my os x mavericks machine (also ubuntu) does not produce the prefixes

UPDATE

if you have bootstrap-sass installed and its mixins are declared somewhere below compass that is why it didn't work. For me anyways.

**Comment by coreylight** [comment]
Thanks @pr1ntr . That's what it was for me.
