### ISSUE TITLE
Invalid gemspec: invalid date format in specification:  "2011-12-24 00:00:00.000000000Z" 

### ISSUE THREAD

**Issue by northk** [Compass/compass#658]
On OS X 10.6.8 with rubygems version 1.8.13 (fron gem -v), after upgrading from an older version of Compass to 0.11.6 (by running "compass install"), I get the following error when executing compass commands:

Invalid gemspec in [/Library/Ruby/Gems/1.8/specifications/ 
compass-0.11.6.gemspec]: invalid date format in specification: 
"2011-12-24 00:00:00.000000000Z" 
NOTE: Gem::Specification#default_executable= is deprecated with no 
replacement. It will be removed on or after 2011-10-01. 
Gem::Specification#default_executable= called from /Library/Ruby/Gems/ 
1.8/specifications/rubygems-update-1.8.2.gemspec:11. 
/Library/Ruby/Site/1.8/rubygems/specification.rb:277:in `_resort!': 
undefined method`name' for nil:NilClass (NoMethodError) 
        from /Library/Ruby/Site/1.8/rubygems/specification.rb:276:in `sort!' 
        from /Library/Ruby/Site/1.8/rubygems/specification.rb:276:in 
`_resort!' 
        from /Library/Ruby/Site/1.8/rubygems/specification.rb:270:in `_all' 
        from /Library/Ruby/Site/1.8/rubygems/specification.rb:402:in`each' 
        from /Library/Ruby/Site/1.8/rubygems/dependency.rb:216:in `find_all' 
        from /Library/Ruby/Site/1.8/rubygems/dependency.rb:216:in 
`matching_specs' 
        from /Library/Ruby/Site/1.8/rubygems/dependency.rb:238:in `to_specs' 
        from /Library/Ruby/Site/1.8/rubygems/dependency.rb:256:in`to_spec' 
        from /Library/Ruby/Site/1.8/rubygems.rb:1182:in `gem' 
        from /usr/bin/compass:18 

The temporary workaround I used is to modify the date in the gemspec to be a valid date, suggested by stackoverflow here: http://stackoverflow.com/questions/5771758/invalid-gemspec-because-of-the-date-format-in-specification

**Comment by scottdavis** [comment]
are you using the default ruby that comes installed on snow leopard?

**Comment by northk** [comment]
Hi Scott,

I'm pretty sure I ran "gem update --system" before upgrading Compass, so I'm not sure if that upgrades ruby or not. If not, then as far as I know I'm using the default ruby that comes installed on Snow Leopard. 

However, I did some Googling and couldn't find an article that definitively asserts which version of ruby comes with Snow Leopard by default, so I can't be sure. It's possible that at some point I did something to upgrade ruby from it's default version, then forgot I did so :)

Thanks,
-NorthK

**Comment by scottdavis** [comment]
Type ruby -v

**Comment by northk** [comment]
ruby -v
ruby 1.8.7 (2010-01-10 patchlevel 249) [universal-darwin10.0]

**Comment by scottdavis** [comment]
@chriseppstein you didn't happen to build the gem with rbx or jruby did you?

**Comment by chriseppstein** [comment]
Unlikely. 

Hunt & pecked on my iPhone... Sorry if it's brief!

**Comment by blissdev** [comment]
Just wanted to note that I'm getting this issue as well, with the same version of Ruby. Updated my gems as well.

**Comment by scottdavis** [comment]
This should be fixed

**Comment by blissdev** [comment]
I'm still getting these issues, should I be awaiting a gem update or something?

**Comment by scottdavis** [comment]
chris pushed a new version try updating

**Comment by blissdev** [comment]
Still getting this in 0.11.7 (Antares). Is this the new pushed version you are referring to?

**Comment by scottdavis** [comment]
what is your ruby gems version?

**Comment by blissdev** [comment]
1.8.15

**Comment by blissdev** [comment]
I'm sorry, this seems to be more of a rubygems bug. I fixed it using this technique: http://paikialog.wordpress.com/2012/01/08/fixes-for-invalid-date-format-specification-in-gemspec/

Also you can fix it by reinstalling gems. Sorry for cluttering this issue.
