### ISSUE TITLE
support for new flexbox spec

### ISSUE THREAD

**Issue by chriseppstein** [Compass/compass#921]
There's a new spec for flexbox. We need to sort out what that means and how to support it going forward.

**Comment by chriseppstein** [comment]
According to @tabatkins The official docs are still a work in progress and there's no conforming implementation. So we'll wait a bit to implement this.

https://twitter.com/chriseppstein/status/210119225031933954

**Comment by tabatkins** [comment]
Specifically, give it two to three months.  Spec'll be CR by then, and we should have just started shipping unprefixed, alongside Opera and Firefox.

The only prefix you'll need to worry about in a few months is MS, because the spec stabilized just a little bit too late to make their IE10 cutoff.

(Unless you want to hack support via old Flexbox (the box-\* stuff), which is possible for some scenarios, but not all.)

**Comment by alanhogan** [comment]
> work in progress and there’s no conforming implementation

Hmm, does that mean the [CanIUse flexbox page](http://caniuse.com/#feat=flexbox) is wrong/out of date for showing lots of Chrome versions in green?

Personally, I would definitely like to see a flexbox mixin that uses the older version when possible. If I have some simple layout issues that could benefit from this sort of thing (and I do), then in the spirit of Compass, I want to declare it once and have it work no matter which browser I’m in (assuming it’s reasonably possible in pure CSS in that browser, natch). I’m okay with a less functional mixin that meets those requirements as opposed to a fully-functional latest-spec-only variant (though both probably ought to exist, so authors can do what they will).

**Comment by tabatkins** [comment]
Yes, the page is wrong.  It's mixing together both the 2009 version of flexbox (where all the properties had the box-\* prefix), and the current one.

At the moment, only Chrome has an implementation of new Flexbox, and we're about to ship breaking changes to make the naming match the Last Call draft that was published today.  Very shortly (in a few months), Chrome, Firefox, and Opera will all be shipping unprefixed Flexbox.  IE10 will also ship Flexbox, but possibly with a prefix.  Obviously, some mixins that paper over the temporary -ms- prefix (if it ends up existing) will be nice.

It is definitely possible to do a lot of the new draft's stuff with the old draft's syntax, so mixins that do so would be good.  The spec has changed very little in overall concept since 2009; the new spec just has a lot of naming changes and a _lot_ of cleanup for usability and detail.

**Comment by alanhogan** [comment]
Fascinating. Thanks.

**Comment by paulirish** [comment]
cc @fyrd we should fix the caniuse page's mention of flexbox. see above comments by tab

also http://html5please.com/#flex and http://www.html5rocks.com/en/tutorials/flexbox/quick/

**Comment by Fyrd** [comment]
Okay, I've updated the note a bit and changed full support to only be Chrome 21 for now. Does this seem like enough?

**Comment by wyuenho** [comment]
The CSS Flexbox spec is in CR status now. It would be nice if this is worked on.

**Comment by ianstormtaylor** [comment]
+1 if it's possible to create helpers that fall back to the old spec. I'd start using flexbox on prod today. Otherwise, just helpers for the new spec and we can start using it when it's a bit more supported. Want this so badly.

**Comment by mirisuzanne** [comment]
I'll look at it when I get a chance, but if you want it so badly you should work on it yourself and submit a patch. I'm happy to give advice along the way.

**Comment by Saturate** [comment]
If nobody else are going to look at it, I might give it a try.

**Comment by JawsomeJason** [comment]
+1 to you, @Saturate!

**Comment by cimmanon** [comment]
Since I couldn't find a proper collection of mixins for the new flexbox, I took a stab at it:  https://gist.github.com/4461470

If I followed the specifications right, this will cover IE10 (early 2012 draft) and the current version of Firefox (2009 draft, caniuse.com claims FF is switching to the current draft with version 20), as well as Opera and Chrome (current draft).  Not sure what draft Safari is following (caniuse.com lists it as following an older one, but doesn't say which).  There's links to the drafts I followed and variables to turn on/off support for the syntax in question.

**Comment by mirisuzanne** [comment]
Very cool! I'm going to play with this. Any chance you want to submit a patch for Compass? 

As I understand, Safari is using the 2009 spec.

**Comment by cimmanon** [comment]
I came across this article (https://www.webkit.org/blog/1972/last-week-in-webkit-flexbox-updates-and-iframes-srcdoc-attribute/), which makes me think at least some versions of Safari might be using the 2012 draft syntax.  I would be interested in submitting a patch if everything looks ok.

**Comment by mirisuzanne** [comment]
Yeah, you may be right. In any case, I think the way you have set up support variables makes everything fairly clear for use. I'll have to play with it some before I can really comment in much detail.

How much is lost in converting between syntaxes? Are there some features that can't be translated?

**Comment by cimmanon** [comment]
I've placed comments in each of the mixins to indicate anything that doesn't have a standard equivalent.  A few property values changed (eg. both drafts used `start` but the standard uses `flex-start`, etc.).

The only thing the 2009 draft is really missing is a way to recreate the modern `flex` and `align-self` properties.  The 2009 `box-flex` is similar to `flex-grow`, but takes a floating point number, and `flex-shrink`/`flex-basis` are non-existent.  It is also missing the `space-around` value for `justify-content` and `align-content` (I've got both of those properties set as `justify` for 2009).

The 2012 draft is missing `flex-grow`/`flex-shrink`/`flex-basis`, but it has the standard version of the `flex` property.

Almost wish I'd been following the evolution of Flexbox throughout the years, would have made this a lot easier to write!  There are lots and lots of articles on each of the different spec implementations or how to tell which article is using which version, but no articles on how one might go about writing code that would work for all of them.

**Comment by tabatkins** [comment]
On Jan 5, 2013 2:52 PM, "cimmanon" notifications@github.com wrote:

> I've placed comments in each of the mixins to indicate anything that
> doesn't have a standard equivalent. A few property values changed (eg. both
> drafts used start but the standard uses flex-start, etc.).
> 
> The only thing the 2009 draft is really missing is a way to recreate the
> modern flex and align-self properties.

What is now align-self used to be built into the box-direction property,
somewhat, and can also be approximated with auto margins.

> The 2009 box-flex is similar to flex-grow, but takes a floating point
> number, and flex-shrink/flex-basis are non-existent.

Old box-flex is roughly flex-grow/shrink combined. (Shrinking works
slightly differently, but it's close.) Old spec just always used
width/height, with no flex-basis equivalent.

> It is also missing the space-around value for justify-content and
> align-content (I've got both of those properties set as justify for 2009).

Yes, that's missing from old flexbox.

> The 2012 draft is missing flex-grow/flex-shrink/flex-basis, but it has
> the standard version of the flex property.

Ignore older drafts of current flexbox. Just use the Editors Draft.
Everyone is supporting it.

That said, you generally shouldn't need to use the flex subproperties.

> Almost wish I'd been following the evolution of Flexbox throughout the
> years, would have made this a lot easier to write!

Feel free to email me with any further questions!

**Comment by cimmanon** [comment]
> Ignore older drafts of current flexbox. Just use the Editors Draft.
> Everyone is supporting it.

I'm not so concerned about desktop browsers, since everyone but IE has auto-update and older versions expire fairly quickly now.  My concern is for mobile devices.  I've been told by the mobile fanatics I work with that mobile users aren't that aggressive when it comes to keeping their software up to date.

**Comment by vdh** [comment]
I've previously tried using both specs for maximum flexbox coverage, and in the end I found they clashed too much to mix together in one selector. I don't think this is a problem that can be solved at Compass' level. It's much easier to detect `flexbox` and `flexboxlegacy` through [Modernizr](http://modernizr.com/) and implement your design needs in each of the two specs, rather than attempt to unify both versions of flexbox through a mixin.

But a caveat is that you'll need to combine selectors, as I found that some browsers will test true for both:

``` scss
.example {
    .flexbox & {
        // 2012 flexbox
    }
    .flexboxlegacy.no-flexbox & {
        // 2009 flexbox
    }
    .no-flexboxlegacy.no-flexbox & {
        // no flexbox support
    }
}
```

An example using the current mixin:

``` scss
.flexbox {
    .outer { @include experimental-value(display, flex, -moz, -webkit, -o, -ms, not -khtml, official); }
    .inner { @include experimental(flex, 1, -moz, -webkit, -o, -ms, not -khtml, official); }
}
.flexboxlegacy.no-flexbox {
    .outer { @include display-box; @include box-orient; width: 100%; }
    .inner { @include box-flex(1); }
}
.no-flexboxlegacy.no-flexbox {
    .outer { display: block; }
    .inner { width: 80%; }
}
```

I think Compass should have distinct legacy and new flexbox mixins to help streamline Modernizr usage, possibly with similar formats, but trying to cover both in a single mixin is just going to cause confusion.

**Comment by cimmanon** [comment]
> I've previously tried using both specs for maximum flexbox coverage, and in the end I found they clashed too much to mix together in one selector.

Where does the clash occur?  As far as I can tell, the only significant difference is with `flex` (standard/2012) and `box-flex` (2009).  Modernizer would have to be used to cover the lack of `flex-basis` from the 2009 spec, but nearly everything else should be able to be covered by a single mixin.

> trying to cover both in a single mixin is just going to cause confusion

Having to learn 3 different names for just about every property is confusing.

**Comment by mirisuzanne** [comment]
The question has to be: can you build a robust/functional layout using both syntax in a single mixin? If not, complex input is preferable to broken output. Looks like we should be able to test that, right?

**Comment by vdh** [comment]
> Where does the clash occur? As far as I can tell, the only significant difference is with flex (standard/2012) and box-flex (2009).

To be honest I can't recall all the clashes that caused my headaches. That `width: 100%;` in my example came from discovering (after much frustration) that Firefox treats `-moz-box` like `inline-block`. At that point I gave up trying to combine selectors.

IMO the 2009 flexbox is useful but nowhere near as fleshed out as the 2012 spec. They're similar enough, but as tabatkins points out they're ever so slightly different. If I need to tweak 2009 already for Firefox, and will need to tweak it again if I want an approximation of `flex-basis` and other 2012 features, I might as well properly separate the styles so they don't contaminate each other.

**Comment by cimmanon** [comment]
Mozilla never implemented the 2009 `box-lines` property (now called `flex-wrap`), but it looks like some Webkit browsers _did_ have it according to this bug report:  https://bugzilla.mozilla.org/show_bug.cgi?id=562073

I've updated the mixin collection (https://gist.github.com/4461470) to have arguments specifying if you only want the 2009 or 2012/standard output.  I'm assuming at this point that the behavior for the 2012 draft is identical to the standard, even though names are different in some instances.  I don't have IE10 or the latest Safari to test/confirm.

**Comment by mirisuzanne** [comment]
I started using these on a project last night. Overall they worked very well for me. For what I was attempting, the official and legacy specs seemed to have very different outcomes - but it was quite easy to turn off the link, and use each one individually. I would vote for pulling this in with the auto-legacy-support turned off by default.

With legacy (2009) turned off, I dont see any support in the lastest Safari.

**Comment by cimmanon** [comment]
@ericam I'm not certain if your oddities were because of the browser implementations of the different specs or because I had made a mistake in matching up a couple of the properties.  I fixed it a couple weeks ago.

When Firefox started placing the Standard flexbox properties as a "disabled by default" feature, one of the known issues was that wrapping wasn't available.  I thought this was going to be something that would be finished before they started shipping it for real, but this doesn't seem to be the case.

The Mozilla team has apparently gone through the effort of convincing Modernizr that they should falsely report FF as supporting flexbox, even though it is feature incomplete:  https://github.com/Modernizr/Modernizr/issues/744

If FF was using a prefix like they _should_ be, this wouldn't be a problem because you could just disable the -moz- prefix and away you go.  However, they're not using prefixes.  Opera is _also_ not using prefixes, but they support wrapping.  The only way to differentiate the two would be to use `@supports`, but I'm not certain what would be the best way to handle this as far as the mixins go.  The only property you need to hide from FF should be the display property itself.

``` css
@supports (flex-wrap: wrap) {
    display: flex;
}
```

Adding an extra argument to the `display-flex` mixin seems like it might be the best way to go about it?

``` scss
@mixin display-flex($type: flex, $legacy: $flex-legacy, $wrap: false) {
    @if $legacy and $wrap == false {
        @include legacy-display-flex($type);
    }

    @include experimental-value(display, flex-translate-value($type, 2012),
        $flex-2012-moz,
        $flex-2012-webkit,
        false,
        $flex-2012-ms,
        false,
        false);

    @include experimental-value(display, $type,
        $flex-moz,
        $flex-webkit,
        $flex-o,
        $flex-ms,
        $flex-khtml,
        $flex-official and not $wrap);

    @if $wrap != false {
        @supports (flex-wrap: wrap) {
            display: $type;
        }
    }
}
```

Example:

``` scss
div {
    @include display-flex($wrap: true);
}
```

Output:

``` css

div {
  display: -webkit-flexbox;
  display: -ms-flexbox;
  display: -webkit-flex;
}
@supports (flex-wrap: wrap) {
  div {
    display: flex;
  }
}
```

**Comment by mirisuzanne** [comment]
I think the problem I was seeing is actually related to a different FF bug, where `%` width and height are ignored on flex children. That's been fixed in the non-prefixed FF implementation.

**Comment by frapontillo** [comment]
There is still an issue, at least for me. I'm using the following SASS:

``` scss
$flex-legacy-enabled: true;

.my-box{
  @include display-flex();
}
```

The generated output, though, is lacking of the ms-prefix (early 2012 spec):

``` css
.my-box{
  display: -webkit-box;
  display: -moz-box;
  display: -webkit-flexbox;
  display: -o-flexbox;
  display: -webkit-flex;
  display: flex;
}
```

I haven't edited @cimmanon's gist, aside from the `shared` import which had to be changed to `compass/css3/shared`.

**UPDATE**: the issue is in the order the experimental value are presented, as `ms` and `o` should be inverted, per [specification](http://compass-style.org/reference/compass/css3/shared/#mixin-experimental-value), in `$flex-support`, `$flexbox-support`, `$box-support`.

**Comment by ProLoser** [comment]
Is there any thought to supporting **BOTH** old and new syntaxes with the same mixins?

Refer to: https://github.com/ProLoser/Flexbox.less/blob/master/flexbox.less

People would be encouraged to use new syntaxes but to improve browser compatibility you can add in older syntaxes too. I realize adding unexpected behaviors may not be within the nature of compass but I thought i'd throw it out there.

**Comment by cimmanon** [comment]
The new mixins _do_ support all 3 specifications with the old 2009 properties suppressed by default.  You just need to change one variable to enable them for all mixins.

**Comment by ProLoser** [comment]
:cry: this is why I love you guys...

**Comment by mirisuzanne** [comment]
Since the feature is pulled in, I'm closing this issue.

**Comment by jareware** [comment]
When are these new mixins slated for release?  Do want.

**Comment by cimmanon** [comment]
If you upgrade to `--pre`, they are there

**Comment by jareware** [comment]
That's excellent news (didn't actually know about the pre-releases)!  And apparently there's work towards a new stable (latest is about to have a birthday :) so I won't bother you about that either.  Thanks for your awesome work!

**Comment by Anahkiasen** [comment]
Is the documentation up to date on this ? http://beta.compass-style.org/reference/compass/css3/box/

**Comment by cimmanon** [comment]
That's the documentation for the old properties, I'm assuming they'll stick around at least for a while.  The new properties are in `compass/css3/flexbox` so their documentation page will be different.
