### ISSUE TITLE
Individual sprite spacing in the sprite-map function doesn't work

### ISSUE THREAD

**Issue by stassop** [Compass/compass#934]
When creating a sprite map with the sprite-map function, individual sprite spacing doesn't work. 

// Works
$icons: sprite-map("icons/*.png", $spacing: 20px);

// Doesn't work
$icons: sprite-map("icons/*.png", $my-icon-spacing: 20px);

Also, it would be nice if Compass gave more control over sprite spacing not only between sprites, but also on the sides. Right now we have to use Compass Magick (https://github.com/StanAngeloff/compass-magick/) for that.

**Comment by chriseppstein** [comment]
The sprite-map function is working as intended. The `$icons-spacing` variable is meant to be configured before importing the magic sprite stylesheet (E.g. `@import "icons/*.png"`), but when you call the `sprite-map function yourself, no such prefixing is needed. In fact, if you run the`compass sprite "icons/*.png"`command you will see that`sprite-map`is called with`$spacing: $icons-spacing` as an argument.

The spacing is needed to keep other images in the sprite map from peeking into the wrong element. In this sense, spacing in directions orthogonal to the sprite is unnecessary as it can be done using padding and margin in css.

**Comment by ezmiller** [comment]
I also have been unable to get this documented feature to work...

**Comment by stereoscott** [comment]
@ezmiller I found that spacing does not work for smart layouts; perhaps that was the same issue for you.

**Comment by rpawel3546** [comment]
Actually that one works:
$icons: sprite-map("icons/*.png", $icons-my-icon-spacing: 20px);

[Compass 0.12.2]

**Comment by scottdavis** [comment]
It's been fixed in 0.13

**Comment by jednano** [comment]
The [CSS Sprite Helpers for Compass documentation](http://compass-style.org/reference/compass/helpers/sprites/) still states that calling `sprite-map` with `$new-spacing: 15px` is the way to do it. This wasn't working for me until I read this thread.

Calling `sprite-map` with `$spacing: 15px` solves this problem for me.

Can the documentation be updated to reflect this?

**Comment by easingthemes** [comment]
Still not working with smart layouts. Works fine with vertical.
So this should not be closed.
Compass 1.0.3 (Polaris)
